dist: trusty
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "Er93Pupm41cnkryzKmu1q7HM7RtoT1WAjTKdx9eT8GeEsyq2b3E3QixEUGi2JwBup/O0GMLR3gY2THmE7zzBVKWPSZ7xHZLfrSADIXfvuZ
JlW5IMqsd0DCgNyNklGNkckDbq1xqWWqsb8FUzXeRFYJvkLAMriLKH+4fGg+3imWShXE0jXTMB7yemEcpCL0XJWPicLrcSqJcob8GDr1bPkCO9z4v/AbZ
/hBnf4ITSza2gDxljDqy5GPQXyT1JrEapZn0OXiLoSbaYlXjvkrndydgCIKN5H8gFW9P2Y6AnPTK6WQ7oyaaZQ+wCRoTSXK6Cw/FzvxfSBB1a5OEWR7pP
hhF7nJ9I6LdSt6eNfLQYsa74EQGYhmEkfhp6QqIumeOa2zpmgc+qajDgM53ow2zQH0zEjGL8rA08wpl1Wrvb+yk+x8abku1U9z/74xxRZyY822TNLsUPv
e4r3HfEmZMnQK3GWqIEH2EMgVeIWt0pXGaUAugfTAl3hd9Fz7SOsf+CrIEjIbGDXw1oZMGAb0mDqX55GVMZvWEg4zDQg7VShuNbugUUDHtWA9AIOLpyuV
+Wccou61hWRveaPY3Z335w8Rl0WFys6+j10nUTNifWBnLKAHer9298mbMGLgHSqpRyl4oBcO0hPcXpyljJ5SpHDxhGRTxxFeSJUR7qNkKEEtg="

addons:
  sonarcloud:
    organization: "toop4eu"
    token:
      secure: "mrW1um/goFkmCZrsUGLODOdaMc72K5SwsFOas1wZuWFQf//76iNSxhqZRGBvDmdIgjzEIC2kPlvdmo7fGZwBO0up27xL74cFtJu7eWzTCdlo/4YVvgOt28qhcu+1D9TH+no+qWmBLG9VXBokruhT/
ZV3V7a/RTbNB7amrNgfezYSfPz7+5TLuZKfNkf4Cl5vIjkwlMGSooiizWAisONvacrqh6Gizxcv2pxh4SAFbyDh4JNV1J4PvexIl8mJO2mB6qc+7V/BY1s7gp7xNchJZQ5OIVGDQSMm/AOiYkWgAqbDjyfiruh6A
/poFzZtDk8FpCRhPLcCeszxstMOy/L8Yrd5DApIoirHXU58hblDLR7eqdRkG3ImQMcWUEsgyFJ3JQ8yO1xRx37/2zTYzvjhn+7DHGtT6KF546Htob0AdmbKtK8LGdZqUX2DPYTYtDlgFM9nWCrojt5D8HN3fY/sE
n7TiFj0Q5KuP9MWX9IG9x6YCrDjDow8O8EVRsxKZB43HJLUeJwMi9Nly4XNZ2KEhyAh7N2yBoaiCOc1lLQvY08BU1CMrkjuWxCOG74pDj+AZzYBJ0uhvG1Ntuitxxf3ObYXYq1wY2UVkH8GiiYMgAmwW012RckdL
PJXADOF92DwETgY9IvRoiJHVXfrvlgu4O3amVUDCWlArpe3dxeQHps="

jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  - mvn test -B -P coverage sonar:sonar
#  - sonar-scanner

cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
