#
# Copyright (C) 2018-2020 toop.eu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:

  loginWebApp:
    image: endimion13/toop-eid:0.5
    ports:
      - 9080:8090
    expose:
      - "9080"
#    network_mode: "host"
    environment:
      - EIDAS_PROPERTIES=http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName,http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName,http://eidas.europa.eu/attributes/naturalperson/DateOfBirth,http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier
      - SP_FAIL_PAGE= http://dc-freedonia.dev.exchange.toop.eu:9084/ui#!loginFailed
      - SP_SUCCESS_PAGE=http://dc-freedonia.dev.exchange.toop.eu:9084/ui
      - SP_METADATA_URL=http://www.host.com:9090/metadata
      - SP_RETURN_URL=http://www.host.com:9090/eidasResponse
      - SP_LOGO=https://www.euritas.eu/wp-content/uploads/2017/10/TOOP-Logo-1024x368.png
      - SP_CONFIG_REPOSITORY=/configEidas/

    volumes:
      - /configEidas-toop:/configEidas
